### ISSUE TITLE
<https://github.com/myTselection/bibliotheek_be/blob/master/custom_components/bibliotheek_be/__init__.py#L19> This is doing I/O during module import, which will hurt Home Assistant startup performance.

### ISSUE THREAD

**Issue by tjorim** [myTselection/bibliotheek_be#18]
<https://github.com/myTselection/bibliotheek_be/blob/master/custom_components/bibliotheek_be/__init__.py#L19> This is doing I/O during module import, which will hurt Home Assistant startup performance.
An alternative is to use this during the setup <https://github.com/home-assistant/core/blob/dev/homeassistant/loader.py#L892>

_Originally posted by @ludeeus in https://github.com/hacs/default/pull/1723#issuecomment-1763328417_

**Comment by myTselection** [comment]
hmm, I have this for all my integrations, as I read the manifest.json for integration constants data such as domain, name, version etc. Manfiest.json is mandatory for each integration.
I don't see much difference with reading this json file compared to loading a const.py file or so instead. But I prefer to only have a single source instead of having duplicated data to maintain. Else I'll forget to increment the version number in manifest or const.py over time.
Loading/importing python files would result in IO too I suppose...the code needs to be loaded with IO as some time anyway...
So I guess I'd prefer to keep as is.

**Comment by ludeeus** [comment]
There is a big difference between reading a file and a static const.

The fact that you do it for all does not make the situation any better.

The suggested alternative provides the same data in a safe manner that does not hold up the startup, while still providing a single source to update (manifest.json), I use this method myself for HACS.

**Comment by myTselection** [comment]
Ok thx for the info! I'll further look into it and update all.
